# Conexión principal
spring.datasource.url=jdbc:oracle:thin:@mibd_high?TNS_ADMIN=C:/Wallet_MIBD
spring.datasource.username=fullstack1
spring.datasource.password=ClaseDuoc123-
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de Hikari para forzar la lectura del Wallet
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=C:/Wallet_MIBD
spring.datasource.hikari.data-source-properties.oracle.net.ssl_server_dn_match=true

spring.datasource.hikari.data-source-properties.oracle.jdbc.fanEnabled=false

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true